### ISSUE TITLE
Fail more gracefully when we can't parse the response returned by Amazon as XML

### ISSUE THREAD

**Issue by rickwaugh1** [aheckmann/node-ses#12]
We have used this module successfully on a few projects, but are having problems now on a new project. I had not had to provide an endpoint before, but had to now, which is fine. Endpoint we are using is email-smtp.us-west-2.amazonaws.com. But when I do it so, and send, I get the following error:

{ [NetworkingError: Parse Error]
  message: 'Parse Error',
  bytesParsed: 0,
  code: 'NetworkingError',
  region: 'us-west-2',
  hostname: 'email-smtp.us-west-2.amazonaws.com',
  retryable: true,
  time: Wed Dec 10 2014 09:18:38 GMT-0800 (PST) } null
NetworkingError: Parse Error
    at CleartextStream.socketOnData (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:511:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at Socket.pipeOnReadable (_stream_readable.js:624:5)

Our code:

var SES = require("node-ses");
var EmailClient = SES.createClient(
{
    key: aws_config["accessKeyId"],
    secret: aws_config["secretAccessKey"],
    amazon: aws_config["endpoint"]
});

EmailClient.sendemail(email, function(err, result)
{
	if (err)
	{
		mainLog.log("error", "Failed to send email " + err.message );
	}
	next(err, result);
});

While troubleshooting, I also saw the following in the AWS console. We have always justed use AWS credentials, so I'm confused:

"To send email through Amazon SES using SMTP, you must create SMTP credentials. SMTP credentials are a username and password that you use when you connect to the Amazon SES SMTP endpoint. You can use the same set of SMTP credentials for all regions in which Amazon SES is available.

To obtain your SMTP credentials, click the button below. For more information about SMTP credentials, click here.

Create My SMTP Credentials
Note: Your SMTP user name and password are not the same as your AWS access key ID and secret access key. Do not attempt to use your AWS credentials to authenticate yourself against the SMTP endpoint. For more information about credential types, click here."

**Comment by markstos** [comment]
Since the issue didn't originate in our module or with Amazon, I'm going to close this issue for now, but would still welcome improvements to handling unexpected responses from Amazon.
