### ISSUE TITLE
attachment support

### ISSUE THREAD

**Issue by webchaz** [aheckmann/node-ses#14]
Is there anyway to add an attachment?

**Comment by rickwaugh1** [comment]
I'm also interested in this. SES does support attachments.

**Comment by markstos** [comment]
Why not use `nodemailer` with the SES transport plugin? It already supports sending mail out through SES using Node.JS and supports attachments.

https://www.npmjs.com/package/nodemailer

    Mark

**Comment by rickwaugh1** [comment]
Yes, I just found that, it looks good, and simple to use. I guess that's where I'm heading. ;)
