### ISSUE TITLE
The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by gmartini20** [aheckmann/node-ses#18]
I'm sending an email using the following code:
```
client.sendemail({
    to: [ data.to.split( ',' ) ],
    from: data.from,
    subject: data.subject,
    message: data.html,
    altText: data.text
  }, function( err, data, res ) {
    console.log( 'sent with success -->', err, data, res );
    if ( err ) {
      callbacks.error();
    } else {
      callbacks.success();
    }
  });
```

and i'm getting the following output:

```
sent with success --> { Type: 'Sender',
  Code: 'SignatureDoesNotMatch',
  Message: 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.' } undefined undefined
```

My key and my secret are correct, is it possible to be an error on the module or I'm doing something wrong?

**Comment by markstos** [comment]
I suspect you are doing something wrong. Set `DEBUG=node-ses` in your environment and try again. 

Reference: https://www.npmjs.com/package/debug

It's working for me. Re-open if your debugging pinpoints in a bug in `node-ses`.

**Comment by markstos** [comment]
If it's helpful, I added some more detailed debugging documentation to our README:

https://github.com/aheckmann/node-ses#debugging
