### ISSUE TITLE
Documentation for published version

### ISSUE THREAD

**Issue by Crazometer** [aheckmann/node-ses#22]
I think it should be made clearer where the documentation for the version published to npm is or when breaking changes are made if you could update the published version that'd be great. Nice library by the way.

**Comment by markstos** [comment]
@Crazometer The documentation for the version published to npmjs.org is on npmjs.org https://www.npmjs.com/package/node-ses

We also keep a Changelog to document key changes: https://github.com/aheckmann/node-ses/blob/master/History.md

If you are reading documentation on Github and not npmjs.org, you should reasonable check that the versions match. Github is where active development happens, npmjs.org is where releases are published.  It is not a goal to keep them in sync as they serve different purposes.

**Comment by Crazometer** [comment]
Thanks for that. The thing that was catching me was the change from sendemail to sendEmail.
