### ISSUE TITLE
One of your two methods doesn't exist

### ISSUE THREAD

**Issue by DelvarWorld** [aheckmann/node-ses#23]
There is no `sendEmail` function. Really hope I'm missing something!

Verified on linux and osx

Version 1.0.2

    $ node
    > var ses = require('node-ses');
    undefined
    > var client = ses.createClient({ key: 'a', secret: 'b' });
    undefined
    > client.sendEmail();
    TypeError: Object #<SESClient> has no method 'sendEmail'

**Comment by markstos** [comment]
You are confusing the published source code from npmjs.org with the
documentation for an unreleased version on Github.
