### ISSUE TITLE
Misinformation in documentation about default endpoint

### ISSUE THREAD

**Issue by DelvarWorld** [aheckmann/node-ses#25]
From the (second result in google for node-ses) "correct" documentation page https://www.npmjs.com/package/node-ses

    `amazon` - [optional] the amazon end-point uri.
    defaults to `https://email.us-west-2.amazonaws.com`

And yet...https://github.com/aheckmann/node-ses/blob/master/lib/ses.js#L6

Verified it's east in the published npm package too, haha :(

**Comment by markstos** [comment]
Thanks for the catch, we'll get this fixed.

On Sat, Aug 22, 2015 at 6:09 PM, Andrew Ray <notifications@github.com>
wrote:

> From the (second result in google for node-ses) "correct" documentation
> page https://www.npmjs.com/package/node-ses
>
> `amazon` - [optional] the amazon end-point uri.
> defaults to `https://email.us-west-2.amazonaws.com`
>
> And yet...https://github.com/aheckmann/node-ses/blob/master/lib/ses.js#L6
>
> Verified it's east in the published npm package too, haha :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aheckmann/node-ses/issues/25>.
>



-- 
    Mark Stosberg
    Senior Systems Engineer
    RideAmigos
