### ISSUE TITLE
Error: Parse Error] bytesParsed: 0, code: 'HPE_INVALID_CONSTANT'

### ISSUE THREAD

**Issue by anup36** [aheckmann/node-ses#26]
var ses = require('node-ses')
  , client = ses.createClient({ key: 'key', secret: 'secret', amazon:'https://email-smtp.us-west-2.amazonaws.com' });
 
// Give SES the details and let it construct the message for you.  
client.sendEmail({
   to: 'anup.panwar36@gmail.com'
 , from: 'anup.panwar36@gmail.com'
 , sender: 'anup.panwar36@gmail.com'
 , bcc: ['anup.panwar6@gmail.com']
 , subject: 'greetings'
 , message: 'your goes here'
 , altText: 'plain text'
}, function (err, data) {
 if(err){
		console.log ('err',err);
	}
	else{
		console.log('data',data);
	}
});

**Comment by markstos** [comment]
You should use the documented [debug mode](https://github.com/aheckmann/node-ses#debugging) review the raw response from the server to understand whether there's an issue in this module or elsewhere. 

If you continue to believe there's a bug this module, please re-open the issue and mention what you think the correct behavior should be, given the response that you see coming back from the server.
