### ISSUE TITLE
Discussion: retry when requests are throttled

### ISSUE THREAD

**Issue by markstos** [aheckmann/node-ses#28]
@aheckmann Any objection to  re-trying requests when they fail to due to AWS throttling them?

There are some downsides:

  * Memory growth due to email queued waiting for retry. This could be potentially be a lot. We either need to be OK with that, or have a maximum queue size to prevent exhausting memory.
  * Potentially calling back *much* later when a response. 

I could also argue that throttling code belongs in an external module, but it's also appealing to have this handled in the single module that all my mail sending gets routed through. 

For comparison, I checked was the AWS  JS SDK does. It doesn't support throttling, I presume because the module is trying to closely mirror the HTTP REST API, which doens't help with throttling / retries, either.

**Comment by aheckmann** [comment]
Sounds reasonable. I don't use this module anymore so feel free to take
this over.

**Comment by markstos** [comment]
@aheckmann Thanks for the reply. Is there another SES mailer that you prefer now instead?

**Comment by aheckmann** [comment]
I'd probably use the official SDK but I haven't looked at it so can't say

**Comment by markstos** [comment]
Note to self: We previously discussed automatic retries in #8  In that ticket the framing was about retrying on /any/ kind of failure.  I think a response from AWS that "you are throttled" is unique case.  We know that the service is up and that we have permission to access it. The only problem is that we are accessing it too quickly. Retrying after some delay could automatically solve that problem. I don't think we need to handle complex cases like huge queue sizes or complex retry algorithms, but I think smoothing over infrequent cases of throttling would be a welcome default behavior.

I'll look some at how the details of this might be implemented and also perhaps look at what an external solution usinig [retry](https://github.com/tim-kos/node-retry) might look like.

**Comment by markstos** [comment]
Another case worth retrying automatically a few times is 'ECONNRESET', which could simply indicate a hiccup with the connection with SES.

**Comment by markstos** [comment]
After more thought, automatic retry should not be a default feature.  Here's why: there are two common cases for email sending and each is interested in different kinds of trade-offs:

  1. **Transanctional Emails** An example would be sending a quick "welcome" email or a "forgot password" email. In this case, The app may be expecting an immediate response from sending the mail. An immediate failure response would be helpful here. It might result in a message to tell the user "Oops! Try again".  An automatic-retry that might result in a 5 minute or 1 hour delay would be highly undesirable here. 
 2. **Bulk email sending** Bulk email sending may go to thousands of emails and generally happen "offline" without someone waiting on them. In this case, the sender *is* very interested in maximum deliverability and not on speed. The bulk sender *would* want automatic retries on connection failures and throtting, because a mailing that completes successfully an hour later is much better that repeatedly fails when you try to send it immediately. 

Some sort of plugin/wrapper/extension could be used to provide this feature. The pull request I just submitted, #35, could help with this, as it allows consuming modules to access the function where we process the AWS response. That's the place where we would decide to retry a failed request if we choose to.
