### ISSUE TITLE
Signature error coming back from Amazon

### ISSUE THREAD

**Issue by satb** [aheckmann/node-ses#30]
Trying to send a simple email. Double checked the SES key and secret are correct...but I keep getting this:

_"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."_

I've used the credentials successfully via the SMTP method and the email was delivered. But I am trying to switch to the API based way but wasn't able to get past this error. Any pointers on where I can start looking?

**Comment by satb** [comment]
I am not sure if the signature version matters, because turning on debug shows me signature version 2 being sent. However, Amazon seems to say they support 3 and 4 versions - http://docs.aws.amazon.com/ses/latest/DeveloperGuide/query-interface-authentication.html

Would that be the problem?

**Comment by markstos** [comment]
I just a test of this library and it "worked for me", but it does sound like we should upgrade the version of the signature we are using.

**Comment by satb** [comment]
Thank you. Its not really a signature issue. The credentials I generated were for SMTP and it worked for those. I was trying to use the same credentials for the API as well. The error message coming back could have been better from Amazon. Thanks for looking and yes, it will be great if the signature can be updated.

**Comment by satb** [comment]
It works by creating a new user with the right permissions
