### ISSUE TITLE
Suggestion: Include string format of email that includes a name

### ISSUE THREAD

**Issue by wamoyo** [aheckmann/node-ses#31]
It is possible to include names in emails like so: `bob ross <bob@ross.com>` It might be nice to put and example of this right in the example on the README. Sadly, most people don't read past the README.

```
client.sendEmail({
   to: 'aaron.heckmann+github@gmail.com'
 , from: 'Frodo Baggins <somewhereOverTheR@inbow.com>'
```

I don't think Frodo Baggins is the best reference, but I leave the humor to the artist : )

**Comment by markstos** [comment]
Are you simply suggesting to update the docs and note the code? We already have an example of using a full name in the Example section of the README:

https://github.com/aheckmann/node-ses#example

If there's something more you have mind, submitting a PR would more clearly express the modification you are suggesting.

**Comment by wamoyo** [comment]
Sorry about that, man. Thanks for pointing out the extended examples.
