### ISSUE TITLE
It is possible to send a from with latin characters?

### ISSUE THREAD

**Issue by germanamz** [aheckmann/node-ses#37]
I'm trying to send an email like this
`From: "México" <mexico@test.com>`

but in the browser the "é" shows as � 

is there possible to send that kind of characters? or what i need to do to make so?

**Comment by markstos** [comment]
Yes, it's possible to send accented characters. 

As mentioned in the README, you must encode your message in UTF-8. It appears you are mixing your encodings somewhere, either trying to send the character in a different encoding or display it in a different encoding.
