### ISSUE TITLE
Rogue template literal which is not transpiled 

### ISSUE THREAD

**Issue by lyuzashi** [aheckmann/node-ses#39]
In the ses.js file, a no-op string is included in the end of the SESClient constructor function https://github.com/aheckmann/node-ses/blob/master/lib/ses.js#L50

This string, while harmless in environments that support template literals, throws an error when evaluated in non-ES6 context. This has manifested in a project of mine that runs an UglifyJS step, as it expects node_modules to be pre-transpiled into ES5.

Please remove this extraneous line.

**Comment by markstos** [comment]
Thanks for the note. I thought this had been recently fixed in the 2.0.2 release, but apparently not. I just published 2.0.3 which removes this stray string.

**Comment by lyuzashi** [comment]
Thanks so much for your quick response and release! Great work on the library – so useful!
