### ISSUE TITLE
AWS SES having problems and the library fails at email.js line 230

### ISSUE THREAD

**Issue by monkeybrother65** [aheckmann/node-ses#42]
Amazon had lots of problems today.  It caused havoc with our system.  When we tried to send an email it looks like amazon is handing you something you arent expecting (bad xml?)  and it brings down my whole node process even though we are wrapping all of our stuff in bluebird promises.  Here is my stack trace:

App 1488 stderr: events.js:141
App 1488 stderr:       throw er; // Unhandled 'error' event
App 1488 stderr:       ^
App 1488 stderr:
App 1488 stderr: TypeError: Cannot read property 'ErrorResponse' of null
App 1488 stderr:     at /home/ec2-user/www/velocicast_prod/node_modules/node-ses/lib/email.js:230:31
App 1488 stderr:     at Parser.<anonymous> (/home/ec2-user/www/velocicast_prod/node_modules/xml2js/lib/xml2js.js:489:18)
App 1488 stderr:     at emitOne (events.js:77:13)
App 1488 stderr:     at Parser.emit (events.js:169:7)
App 1488 stderr:     at Parser.exports.Parser.Parser.parseString (/home/ec2-user/www/velocicast_prod/node_modules/xml2js/lib/xml2js.js:499:16)
App 1488 stderr:     at Parser.parseString (/home/ec2-user/www/velocicast_prod/node_modules/xml2js/lib/xml2js.js:7:59)
App 1488 stderr:     at Email._processResponse (/home/ec2-user/www/velocicast_prod/node_modules/node-ses/lib/email.js:219:22)
App 1488 stderr:     at Request._callback (/home/ec2-user/www/velocicast_prod/node_modules/node-ses/lib/email.js:197:10)
App 1488 stderr:     at Request.self.callback (/home/ec2-user/www/velocicast_prod/node_modules/request/request.js:186:22)
App 1488 stderr:     at emitTwo (events.js:87:13)
App 1488 stderr:     at Request.emit (events.js:172:7)
App 1488 stderr:     at Request.<anonymous> (/home/ec2-user/www/velocicast_prod/node_modules/request/request.js:1081:10)
App 1488 stderr:     at emitOne (events.js:77:13)
App 1488 stderr:     at Request.emit (events.js:169:7)
App 1488 stderr:     at IncomingMessage.<anonymous> (/home/ec2-user/www/velocicast_prod/node_modules/request/request.js:1001:12)
App 1488 stderr:     at IncomingMessage.g (events.js:260:16)
App 1488 stderr:     at emitNone (events.js:72:20)
App 1488 stderr:     at IncomingMessage.emit (events.js:166:7)
App 1488 stderr:     at endReadableNT (_stream_readable.js:921:12)
App 1488 stderr:     at nextTickCallbackWith2Args (node.js:442:9)
App 1488 stderr:     at process._tickDomainCallback (node.js:397:17)

Your code looks like you have good, responsible error handling in there for the most part.  However, it looks like you need to test like this:

if(result && result.ErrorResponse){
    return callback(result.ErrorResponse.Error)
}else{
   return callback('unexpected response from SES');
}

**Comment by markstos** [comment]
I agree we could improve our error handling here. Looking now.

**Comment by markstos** [comment]
Fixed in v2.0.4. 

Thanks for the report.
