### ISSUE TITLE
Set ConfigurationSetName

### ISSUE THREAD

**Issue by fscardua** [aheckmann/node-ses#47]
How can I set the ConfigurationSetName ?

**Comment by markstos** [comment]
It is not currently supported. Feel free to propose how we would update the interface to support it in a comment or via pull request.

**Comment by tsudharsanprdxn** [comment]
@markstos : Has the feature to set configurationSetName been added yet?

**Comment by markstos** [comment]
No

**Comment by markstos** [comment]
Fixed in #53.
