### ISSUE TITLE
Using within Lambda

### ISSUE THREAD

**Issue by sayanriju** [aheckmann/node-ses#48]
How to pass credentials to node-ses `createClient()` so that it can send an email from within a Lmbda invocation?

Using the `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` from the environment variables automatically available inside the lambda doesn't work (not without also specifying session token, apparently)

**Comment by markstos** [comment]
Fix published in 2.1.0 today. I also updated the README to reflect the changes.
