### ISSUE TITLE
How do i send html emailer via raw message?

### ISSUE THREAD

**Issue by tsudharsanprdxn** [aheckmann/node-ses#50]
@markstos Can you please help in understanding how to send html emailer template in raw message.

**Comment by markstos** [comment]
@tsudharsanprdxn You've made no attempt to show that you've tried to figure this out on your own, so no.

**Comment by stuphodgson** [comment]
> @markstos Can you please help in understanding how to send html emailer template in raw message.

This should help... https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/ses-examples-sending-email.html

I thought collaborators generally helped other users!
