### ISSUE TITLE
Signature Version 4 requests that include a signed \'connection\' header

### ISSUE THREAD

**Issue by alfonsoterron** [aheckmann/node-ses#70]
Hi all,

We are getting this issue, this appeared after AWS upgrade on March 30th.

Locally we were able to fix it comment the following lines:

node-ses/lib/email.js

line 206: `//headers['Connection'] = 'Keep-Alive';`
line 212: `//    , headers: headers`

If you are able to push this fix we really appreciate it.

Thanks!

**Comment by markstos** [comment]
This was fixed and released in 3.0.3 of October of last year: https://github.com/aheckmann/node-ses/pull/68

**Comment by alfonsoterron** [comment]
Oh, we were in the static version!. thanks!
