### ISSUE TITLE
InvalidClientTokenId

### ISSUE THREAD

**Issue by woutercouvaras** [aheckmann/node-ses#73]
Hi,

We're using [this package](https://github.com/ericraio/parse-server-simple-ses-adapter), which is a thin wrapper around node-ses.  We started receiving the above mentioned AWS error when sending mails.  I dually checked to see if node-ses was updated to handle v4 signing, which it is (thank you for your work on this package).

I also checked to see that the wrapper we're using was updated to use the correct version of node-ses, which it is.

Is anyone else receiving these errors?  Is there anything we need to do, apart from be on the latest packages?

I'd appreciate any help.

Thanks!

**Comment by woutercouvaras** [comment]
Tested node-ses on it's own - all good.  Not sure why where things are falling over for me.

**Comment by markstos** [comment]
I'm the sole maintainer and don't use this project myself anymore. I recommend using the AWS SDK or Nodemailer as a replacement.

**Comment by woutercouvaras** [comment]
Thanks Mark.  All the best!
