### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by epalmen** [aheckmann/node-ses#82]
Iam using this package it is great. But it uses some outdated dependencies.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

Will you maintain this package. Else I have to change and start using the AWS SDK.

Cheers,
Erik

**Comment by markstos** [comment]
There's also option three: you maintain the package.

**Comment by aheckmann** [comment]
Closing. [This project is no longer maintained](https://github.com/aheckmann/node-ses?tab=readme-ov-file#deprecated).
