### ISSUE TITLE
[Question] Are AWS access keys required when running within AWS?

### ISSUE THREAD

**Issue by tiagojsag** [aheckmann/node-ses#83]
Hi,

First of all, thanks for creating and maintaining this project.

On to my question: can this lib be used within AWS infrastructure (say running in EC2) without explicitly passing the access key and secret? Judging by the code, my guess is "no", but I wanted to confirm with you, the maintainer(s). It has long been established that having IAM credentials being passed around inside AWS is a bad practice, and IAM roles should be used instead. Just wanted to confirm if that's an option with this lib

Thanks!

**Comment by bschulz87** [comment]
I'd like to know this as well.

**Comment by aheckmann** [comment]
Closing. [This project is no longer maintained](https://github.com/aheckmann/node-ses?tab=readme-ov-file#deprecated).
