### ISSUE TITLE
Recommending deprecating / archiving

### ISSUE THREAD

**Issue by markstos** [aheckmann/node-ses#84]
@aheckmann I'm writing as last official maintainer for this project. 

Since you are the repo owner, I recommend deprecating and archiving this project and pointing people to using the AWS official client instead:

https://www.npmjs.com/package/@aws-sdk/client-ses

This project was created along before that, when the only official option was a giant, monolithic SDK that did far more than sending email. Had the very focused @aws-sdk/client-ses module existed earlier, I doubt this project would have been created. 

Another option that people can use that supports multiple backends is nodemailer.

I have moved on to using those options myself and no longer this project myself, which is why I'm no longer maintaining it.

**Comment by aheckmann** [comment]
Sounds good
